(function(){
  const {createClient}=window.supabase;const url=window.SUPABASE_URL,key=window.SUPABASE_PUBLISHABLE_KEY;
  const authPanel=document.getElementById('authPanel'), adminPanel=document.getElementById('adminPanel'), msg=document.getElementById('msg'), authMessage=document.getElementById('authMessage');
  if(!url||url.includes('PASTE_')||!key||key.includes('PASTE_')){authMessage.textContent='Pehle config.js mein Supabase URL aur Publishable key paste karo.';return;}
  const sb=createClient(url,key);
  async function isAdmin(){const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data,error}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();return !error&&data?.role==='admin';}
  async function refresh(){const admin=await isAdmin();authPanel.classList.toggle('hidden',admin);adminPanel.classList.toggle('hidden',!admin);if(admin)loadContent();}
  document.getElementById('authForm').addEventListener('submit',async e=>{e.preventDefault();authMessage.textContent='Login ho raha hai…';const {error}=await sb.auth.signInWithPassword({email:email.value.trim(),password:password.value});authMessage.textContent=error?error.message:'Login successful.';if(!error)refresh();});
  document.getElementById('signupBtn').addEventListener('click',async()=>{authMessage.textContent='Account create ho raha hai…';const {data,error}=await sb.auth.signUp({email:email.value.trim(),password:password.value});authMessage.textContent=error?error.message:(data.session?'Account created.':'Account created. Email confirmation setting ke hisaab se inbox check karo.');});
  document.getElementById('logoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();location.reload();});
  async function loadContent(){const {data:tests,error}=await sb.from('tests').select('id,name,exam,duration_minutes,negative_marking').order('created_at',{ascending:false});if(error){msg.textContent=error.message;return;}document.getElementById('statTests').textContent=tests.length;document.getElementById('questionTest').innerHTML=tests.length?tests.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join(''):'<option value="">Pehle test banao</option>';let total=0;let html='';for(const t of tests){const {data:qs}=await sb.from('questions').select('id,question_text,correct_option,question_order').eq('test_id',t.id).order('question_order');total+=(qs||[]).length;html+=`<div class="admin-item"><div class="item-row"><div><div class="item-title">TEST: ${esc(t.name)}</div><div class="item-meta">${esc(t.exam)} • ${t.duration_minutes} min • −${Number(t.negative_marking).toFixed(3)} • ${(qs||[]).length} Q</div></div><button class="danger" data-del-test="${t.id}">Delete Test</button></div></div>`;(qs||[]).forEach(q=>html+=`<div class="admin-item"><div class="item-row"><div><div class="item-title">Q${q.question_order}: ${esc(q.question_text)}</div><div class="item-meta">Correct: ${String.fromCharCode(65+q.correct_option)}</div></div><button class="danger" data-del-q="${q.id}">Delete Q</button></div></div>`)}document.getElementById('statQuestions').textContent=total;document.getElementById('manageList').innerHTML=html||'<p>No content yet.</p>';document.querySelectorAll('[data-del-test]').forEach(b=>b.onclick=()=>deleteTest(b.dataset.delTest));document.querySelectorAll('[data-del-q]').forEach(b=>b.onclick=()=>deleteQ(b.dataset.delQ));}
  document.getElementById('testForm').addEventListener('submit',async e=>{e.preventDefault();msg.textContent='Saving test…';const {error}=await sb.from('tests').insert({name:testName.value.trim(),exam:testExam.value,duration_minutes:Number(testTime.value),negative_marking:Number(negative.value)});msg.textContent=error?error.message:'Test added online ✅';if(!error){e.target.reset();testTime.value=30;negative.value='0.333';loadContent();}});
  document.getElementById('questionForm').addEventListener('submit',async e=>{e.preventDefault();const testId=questionTest.value;if(!testId){msg.textContent='Pehle test create karo.';return;}msg.textContent='Saving question…';const {error}=await sb.from('questions').insert({test_id:testId,question_text:questionText.value.trim(),option_a:optA.value.trim(),option_b:optB.value.trim(),option_c:optC.value.trim(),option_d:optD.value.trim(),correct_option:Number(correct.value),explanation:explanation.value.trim(),question_order:Number(questionOrder.value)});msg.textContent=error?error.message:'Question added online ✅';if(!error){e.target.reset();questionOrder.value=1;loadContent();}});
  async function deleteTest(id){if(!confirm('Test aur uske questions delete karne hain?'))return;const {error}=await sb.from('tests').delete().eq('id',id);msg.textContent=error?error.message:'Test deleted';if(!error)loadContent();}
  async function deleteQ(id){if(!confirm('Question delete karna hai?'))return;const {error}=await sb.from('questions').delete().eq('id',id);msg.textContent=error?error.message:'Question deleted';if(!error)loadContent();}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
  refresh();
})();
