(async function(){
  const {createClient}=window.supabase;const url=window.SUPABASE_URL,key=window.SUPABASE_PUBLISHABLE_KEY;const main=document.querySelector('main');
  if(!url||url.includes('PASTE_')||!key||key.includes('PASTE_')){main.innerHTML='<section class="panel"><h2>Supabase setup pending</h2><p>config.js complete karo.</p></section>';return;}
  const sb=createClient(url,key);const id=new URLSearchParams(location.search).get('id');let test,qs=[],idx=0,answers=[];let seconds=0;let timerId;
  const {data:t,error:te}=await sb.from('tests').select('*').eq('id',id).maybeSingle();if(te||!t){main.innerHTML='<section class="panel"><h2>Test nahi mila.</h2><a class="btn primary" href="index.html">Back Home</a></section>';return;}test=t;
  const {data:q,error:qe}=await sb.from('questions').select('id,question_text,option_a,option_b,option_c,option_d,correct_option,explanation,question_order').eq('test_id',id).order('question_order');if(qe||!q?.length){main.innerHTML='<section class="panel"><h2>Is test mein questions nahi hain.</h2><a class="btn primary" href="index.html">Back Home</a></section>';return;}qs=q;answers=Array(qs.length).fill(null);seconds=test.duration_minutes*60;
  document.getElementById('testTitle').textContent=test.name;document.getElementById('examTag').textContent=test.exam;document.getElementById('testMeta').innerHTML=`<span>📝 ${qs.length} Questions</span><span>⏱ ${test.duration_minutes} min</span><span>−${Number(test.negative_marking).toFixed(3)} per wrong</span>`;
  function render(){const x=qs[idx];document.getElementById('qNumber').textContent=`Question ${idx+1} / ${qs.length}`;document.getElementById('answeredCount').textContent=`${answers.filter(a=>a!==null).length}/${qs.length} answered`;document.getElementById('questionText').textContent=x.question_text;const opts=[x.option_a,x.option_b,x.option_c,x.option_d];document.getElementById('options').innerHTML=opts.map((o,i)=>`<button class="option ${answers[idx]===i?'selected':''}" data-i="${i}"><strong>${String.fromCharCode(65+i)}.</strong> ${esc(o)}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{answers[idx]=Number(b.dataset.i);render()});document.getElementById('prevBtn').disabled=idx===0;document.getElementById('nextBtn').textContent=idx===qs.length-1?'Finish →':'Next →';document.getElementById('paletteGrid').innerHTML=qs.map((_,i)=>`<button class="palette-btn ${i===idx?'current ':''}${answers[i]!==null?'answered':''}" data-i="${i}">${i+1}</button>`).join('');document.querySelectorAll('.palette-btn').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.i);render()});}
  function tick(){const m=Math.floor(seconds/60),s=seconds%60;document.getElementById('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(seconds<=0){clearInterval(timerId);submit();}else seconds--;}
  async function submit(){if(window.submitting)return;window.submitting=true;const correct=answers.reduce((n,a,i)=>n+(a===qs[i].correct_option?1:0),0),wrong=answers.reduce((n,a,i)=>n+(a!==null&&a!==qs[i].correct_option?1:0),0),skipped=answers.filter(a=>a===null).length,score=correct-(wrong*Number(test.negative_marking));const {data:{user}}=await sb.auth.getUser();const result={testId:test.id,testName:test.name,total:qs.length,correct,wrong,skipped,score,negative:Number(test.negative_marking),accuracy:(correct/(correct+wrong||1))*100,answers};localStorage.setItem('chitranshLastResult',JSON.stringify(result));if(user){await sb.from('test_results').insert({user_id:user.id,test_id:test.id,total_questions:qs.length,correct_answers:correct,wrong_answers:wrong,skipped_answers:skipped,score:score,accuracy:result.accuracy});}location.href=`result.html?id=${encodeURIComponent(test.id)}`}
  document.getElementById('prevBtn').onclick=()=>{if(idx>0){idx--;render()}};document.getElementById('nextBtn').onclick=()=>{if(idx<qs.length-1){idx++;render()}else if(confirm('Test submit karna hai?'))submit()};document.getElementById('submitTop').onclick=()=>{if(confirm('Kya aap test submit karna chahte ho?'))submit()};function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}render();tick();timerId=setInterval(tick,1000);
})();
